defaults:
  env:
    apiKey: secret:api_key
  resources:
    instance-type: C4

jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/sethvanb/SpringBoard.git

  TrainModel:
    env:
      EPOCHS: "3"
      MODEL_DIR: /trained-model/1
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      trained-model:
        type: dataset
        with:
          ref: mlb-ml-model
    uses: script@v1
    with:
      script: |-
        cd /inputs/repo
        python train.py
        cp -R /trained-model /outputs/trained-model
      image: 'nvcr.io/nvidia/tensorflow:21.09-tf2-py3'

  UploadModel:
    inputs:
      model: TrainModel.outputs.trained-model
    outputs:
      model-id:
        type: string
    needs:
      - TrainModel
    uses: create-model@v1
    with:
      name: trained-model
      type: Tensorflow